name       : kitemviews
version    : 5.66.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kitemviews-5.66.0.tar.xz : 026461fa2e3e0237a56eb18a2817453c788514578f27a4aa0832b85fe98a09ab
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
