name       : kitemviews
version    : 5.64.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kitemviews-5.64.0.tar.xz : 0b3f8a0116c042ae187b67f35ffd40872352b91f5f236d19dd26ffad8db83fee
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
