name       : kitemviews
version    : 5.39.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.39/kitemviews-5.39.0.tar.xz : d069da87a28b373676b7bda1a1474c5f8c815441041cbc5af52d7c1a5a4a885e
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
