name       : kitemviews
version    : 5.54.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kitemviews-5.54.0.tar.xz : b38e892c42681ef94a978e11bbaa83568004afc6972a11d6ce0789193b8a89b3
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
