name       : kitemviews
version    : 5.69.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kitemviews-5.69.0.tar.xz : 9e17697ccdfd6abc6199abdaa23e6869a0904eb284d285bb2a2c3e1f2d0f6947
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
