name       : kitemviews
version    : 5.94.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kitemviews-5.94.0.tar.xz : 5b75334b719ce07f4aa33236ef4bd11829504ff381670818ef57a7526938b52e
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
