name       : kitemviews
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/kitemviews-5.36.0.tar.xz : 74ead758a65746d9404bfa4cfbebb95fdada196246b38b07b68c7094cdf22a06
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
