name       : kitemviews
version    : 5.76.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kitemviews-5.76.0.tar.xz : b102cb67513d804fd7eed2ae20bb4ba679d38de4f236de6bc03709ff0c0bc001
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
