name       : kitemviews
version    : 5.52.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kitemviews-5.52.0.tar.xz : eb71fe0c674123285cff66d67c2c930b2b6c44a63998279b67a67c30b1fe07db
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
