name       : kitemviews
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kitemviews-5.25.0.tar.xz : 98078899862514cc16ceff0275fe5eab43bc14e8f361af11a8e3c45a2fc5a284
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
