name       : kitemviews
version    : 5.96.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kitemviews-5.96.0.tar.xz : 8b9a6404b5a84c9142008c3fe840c7ba4a3fbf8f77253a5105e4512ecd1726f3
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
