name       : kitemviews
version    : 5.68.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kitemviews-5.68.0.tar.xz : 5196885ac42347d67779df61a03d7f9c54f38053ff91348ef6fdc08439b4742f
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
