name       : kitemviews
version    : 5.80.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kitemviews-5.80.0.tar.xz : 9702a531799c5f99810beaa64efeb0683d5ae8d4c4933de6906d205f192635c9
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
